# Generated by Django 5.1.2 on 2025-11-05 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to_task_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bugreport',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('owner', 'title')},
        ),
    ]
