# Generated by Django 5.2.7 on 2025-11-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_bugreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
    ]
