# Generated by Django 5.2.7 on 2025-11-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_note_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bugreport',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
