# Generated by Django 5.2.7 on 2025-11-05 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_bugreport_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bugreport',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('owner', 'title')},
        ),
    ]
